apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-ns
  namespace: test-ocp4-new-workers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-ocp4-new-workers
  template:
    metadata:
      labels:
        app: test-ocp4-new-workers
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.1
        ports:
        - containerPort: 80
        - containerPort: 443